name: generate_sbom
run-name: gen_sbom_${{ github.event.pull_request.head.sha }}
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

env:
  SBOM_FILENAME: ${{ github.event.repository.name }}-${{ github.event.pull_request.head.sha }}.json

jobs:
  generate_sbom:
    name: Generate sBOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup cdxgen
        shell: bash
        run: npm install -g @cyclonedx/cdxgen@8.4.2
      
      - name: Generate sBOM
        shell: bash
        run: cdxgen ./ -o ${{env.SBOM_FILENAME}}

      - uses: actions/upload-artifact@v3
        with:
          name: cyclonedx-sbom
          path: ${{env.SBOM_FILENAME}}

    