name: Publish SBOM
run-name: Test reusable workflow

on:
  push:
    branches:
      - main
      - master
jobs:
  call-workflow-1-in-local-repo:
    uses: test-tranferwise/required-workflows/.github/workflows/generate_and_publish_sbom.yaml@main
