name: generate_sbom
run-name: Generate sBOM
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

env:
  SBOM_FILENAME: ${{ github.event.repository.name }}-${{ github.event.pull_request.head.sha }}.json

jobs:
  generate_sbom:
    name: Generate sBOM
    runs-on: ubuntu-latest
    steps:
      - name: Setup cdxgen
        shell: bash
        run: npm install -g @cyclonedx/cdxgen@8.2.4 
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Generate sBOM
        id: generate-sbom
        shell: bash
        run: cdxgen ./ -o ${{env.SBOM_FILENAME}} 
      
      - name: create file
        shell: bash
        run: echo "hello" >> hello.txt 

      - name: view files
        shell: bash
        run: ls

      

      