name: Generate sBOM
run-name: Generate sBOM
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - closed


jobs:
  generate_sbom:
    name: Generate sBOM
    runs-on: ubuntu-latest
    steps:
      - name: Show github.sha
        shell: bash
        run: echo ${{ github.sha }}
      
      - name: Show github.event.head.sha
        shell: bash
        run: echo ${{ github.event.pull_request.head.sha }}
      
      - name: Show github.sha on merge
        if: github.event.pull_request.merged == true
        shell: bash
        run: echo ${{ github.sha }}
      
      - name: Show github.event.head.sha on merge
        if: github.event.pull_request.merged == true
        shell: bash
        run: echo ${{ github.event.pull_request.head.sha }}
      

      