name: generate_sbom
run-name: Generate sBOM
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

env:
  SBOM_FILENAME: ${{ github.event.repository.name }}-${{ github.event.pull_request.head.sha }}.json

jobs:
  generate_sbom:
    name: Generate sBOM
    runs-on: ubuntu-latest
    steps:
      - name: Setup cdxgen
        shell: bash
        run: npm install -g @cyclonedx/cdxgen@8.2.4 
      
      - name: Generate sBOM
        id: generate-sbom
        shell: bash
        run: cdxgen ./ -o ${{ env.SBOM_FILENAME }}

      - uses: actions/upload-artifact@v3
        id: upload-artifact
        continue-on-error: true
        with:
          name: cyclonedx-sbom
          path: ${{ env.SBOM_FILENAME }}
          if-no-files-found: error
      

      