name: generate_sbom
run-name: gen_sbom_${{ github.event.pull_request.head.sha }}
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

env:
  SBOM_FILENAME: ${{ github.event.repository.name }}-${{ github.event.pull_request.head.sha }}.json

jobs:
  generate_sbom:
    name: Generate sBOM
    runs-on: ubuntu-latest
    steps:
      - name: Setup cdxgen
        shell: bash
        run: npm install -g @cyclonedx/cdxgen@8.1.1 
      
      - name: Generate sbom
        shell: bash
        run: cdxgen ./ -o sbom.json
      
      - name: make file
        shell: bash
        run: echo {msg:"Hello World"}>>hello.json

      - uses: actions/upload-artifact@v3
        with:
          name: cyclonedx-sbom
          path: sbom.json

    